# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lGUXy3f4V4dI1-cgMaIW_WVSp_LWXzxI
"""




import sys
import subprocess
import pkg_resources

subprocess.run([sys.executable,"-m", 'apt' ,'install' ,'ffmpeg','google-api-python-client', 'google-auth-httplib2','google-auth-oauthlib'])

required  = {'pytube', 'gdown','spleeter','streamlit','pydrive','pygithub'} 
installed = {pkg.key for pkg in pkg_resources.working_set}
missing   = required - installed

if missing:
    # implement pip as a subprocess:
    subprocess.check_call([sys.executable, '-m', 'pip', 'install', *missing])



import spleeter
import os

import tqdm
from pytube import YouTube
import os
from pathlib import Path
import subprocess
import streamlit as st
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from zipfile import ZipFile
import os
from os.path import basename
import time
import base64
from github import Github
from zipfile import ZipFile
import os
from os.path import basename

ACCESS_TOKEN = "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"
INTERNAL_FILE = "/content/vocals.mp3"
FOLDER_EMPL_IN_GIT = "data/"
FULL_NAME='TEST22'


def add_or_update_in_git(initial_file,fullname):
    g = Github("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")

    repo = g.get_user().get_repo("ytdlspleeter")
    all_files = []
    contents = repo.get_contents("")
    print(contents)

    while contents:
        file_content = contents.pop(0)
        if file_content.type == "dir":
            contents.extend(repo.get_contents(file_content.path))
        else:
            file = file_content
            all_files.append(str(file).replace('ContentFile(path="', '').replace('")', ''))

    with open(initial_file, 'rb',) as file:
      bytes = file.read()
      content = base64.b64encode(bytes)

    # Upload to github
    if 'data/'+fullname+'.txt' in all_files:
        contents = repo.get_contents('data/'+fullname+'.txt')
        repo.update_file(contents.path, "updating files "+fullname , content, contents.sha, branch="main")
        return fullname + ' UPDATED'
    else:
        repo.create_file('data/'+fullname+'.txt', "creating files " +fullname, content, branch="main")
        return fullname + ' CREATED'



  
cwd=str(os.getcwd())

def save(fname):
  savecwd=cwd
  dirName=cwd+'/audio/'+fname
  with ZipFile(fname+'.zip', 'w') as zipObj:
    for folderName, subfolders, filenames in os.walk(dirName):
      for filename in filenames:
        filePath = os.path.join(folderName, filename)
        zipObj.write(filePath, basename(filePath))
  add_or_update_in_git(fname+'.zip',fname)



def youtube2mp3 (url,outdir,fname):
    # url input from user
    yt = YouTube(url)

    ##@ Extract audio with 160kbps quality from video
    video = yt.streams.filter(only_audio=True,abr='160kbps').last()

    ##@ Downloadthe file
    out_file = video.download(output_path=outdir,filename=fname)
    base, ext = os.path.splitext(out_file)
    new_file = Path(f'{base}.mp3')
    os.rename(out_file, new_file)
    ##@ Check success of download
    if new_file.exists():
        print(f'{yt.title} has been successfully downloaded.')
        idsave=fname
        fnamesave=fname+'.mp3'
        fname=cwd+"/audio/"+fname+'/'+fname+'.mp3'
        out=cwd+'/audio/'
        subprocess.run(["spleeter", "separate", fname ,"-p" "spleeter:5stems", "-c", "mp3", "-o", out], capture_output=True)
        audio_file = open(fname, 'rb')
        audio_bytes = audio_file.read()
        st.audio(audio_bytes, format='mp3')
        user_input=st.text_input(fname)
        save(idsave)
    else:
        print(f'ERROR: {yt.title}could not be downloaded!')
    

def audiodl(id):
  id=str.split(id)
  print(id)
  for i in range(0,len(id)):
    url='www.youtube.com/watch?v='+id[i]
    youtube2mp3(url,cwd+'/audio/'+str(id[i])+"",str(id[i]))  

user_input1 = st.text_input("insère ton lien poto", '')
while len(user_input1)==0:
  time.sleep(5)
a=audiodl(user_input1)
user_input=st.text_input(cwd)
